apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: demo-flux
  namespace: flux-system
spec:
  interval: 1m
  # TODO: replace with your repository URL (https or ssh)
  url: "https://github.com/kaustubhsonar/demo.flux"
  ref:
    branch: main
