apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: demo-flux
  namespace: flux-system
  annotations:
    "demo.flux/notes": "bootstrap --path should point to the folder containing Flux manifests (flux-system). Helm charts live in ./helm-charts and are referenced from HelmRelease resources in flux-system."
spec:
  interval: 1m
  url: "https://github.com/kaustubhsonar/demo.flux"
  ref:
    branch: main
