apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: demo-flux
  namespace: flux-system
spec:
  interval: 1m
  # Replace with your repository URL (HTTPS or SSH)
  url: "https://github.com/kaustubhsonar/demo.flux.git"
  # optional: set branch if not main
  ref:
    branch: main
  # optional: if private repo, reference a secret:
  # secretRef:
  #   name: flux-system
