apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-nginx" .Release.Name }}
  labels:
    app: {{ printf "%s-nginx" .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-nginx" .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-nginx" .Release.Name }}
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
